version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10-stretch-browsers
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Lint
          command: npm run lint:ci

      - run:
          name: Build
          command: npm run build:prod

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        

